version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minio}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minio123}
      - KEYCLOAK_URL=${KEYCLOAK_URL:-http://keycloak:8080}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-file-management}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-file-management-client}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET:-Jd3g4wqboo1o18sjm4xac7zRsv65sXr0}
      - PYTHONUNBUFFERED=1
    depends_on:
      - minio
      - keycloak
    restart: unless-stopped

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY:-minio123}
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    restart: unless-stopped

volumes:
  minio_data: